default:
  # Specifies what should be the default behaviour. Note that you need to set KeepInventory = True on your world's config for this plugin to work
  KeepItems: false,
  # Should the player keep their items if they die?

  KeepXP: false,
  # Should the player keep their XP if they die?

  DropItems: true
  # Only runs if keepitems = false. Should the player drop their items when they die?

  DropXP: true
  # Only runs if keepitems = false. Should the player drop their XP when they die?

  LimitXP: 91
  # Set a limit to dropped XP in points. 91 is 7 levels and emulates Minecraft's Default behvaiour.
  # Set LimitXP to 0 to impose no limit on dropped XP
  # This only runs if the user has disabled keepinventory

  AllowChoice: true
  # Allow players to choose whether they want their inventory kept for this world.

# You can specify specific settings for other worlds. See the example below:

exampleworld:
  KeepItems: true
  KeepXP: true
  DropItems: true
  DropXP: true
  LimitXP: 0
  AllowChoice: true

runinworlds:
  - "*" #Keep the star to run in every world (if keepinventory is true; setting keepinventory = false disables this plugin in that particular world)